### ISSUE TITLE
Kill All process except one ! 

### ISSUE THREAD

**Issue by Nebula-Spark** [xsellier/node-ps#3]
Hi ,
I just want to Kill all running process  in windows ,

example 
like kill all process expect  chrome.exe 
Is there anyway to Do this ?

btw i am just newbie here ,

it would be great if u can give any solution for this ,

**Comment by xsellier** [comment]
Something like that, I have not tested it.

```js
var options = {
  name: /\b(?!chrome\b).*/i
};

ps.list(options, function(err, result) {
  // Add error handling
  var options = {
    pidList: result,
    signal: '-9'
  };

  ps.kill(options, function(err) {
    // Add error handling
  });
});
```

**Comment by Nebula-Spark** [comment]
@xsellier 
 I am getting the following error 
ZoneAwareError__zone_symbol__error: Error: Process exited with code 1, output:
ERROR: Invalid syntax. '/t' option is not allowed more than '1' time(s).
Type "TASKKILL /?" for usage.



    at ChildProcess.eval (eval at <anonymous> (http://localhost:4000/js/app.js:5428:1), <anonymous>:152:12) [<root>]
    at emitTwo (events.js:106:13) [<root>]
    at ChildProcess.emit (events.js:191:7) [<root>]
    at maybeClose (internal/child_process.js:885:16) [<root>]
    at Socket.<anonymous> (internal/child_process.js:334:11) [<root>]
    at emitOne (events.js:96:13) [<root>]
    at Socket.emit (events.js:188:7) [<root>]
    at Pipe._handle.close [as _onclose] (net.js:501:12) [<root>]message: (...)name: (...)originalStack: (...)stack: (...)toSource: ()toString: ()zoneAwareStack: (...)get message: ()set message: (value)get name: ()set name: (value)get originalStack: ()set originalStack: (value)get stack: ()set stack: (value)get zoneAwareStack: ()set zoneAwareStack: (value)__proto__: Object


ps.list(options, function(err, result) {
  // Add error handling
console.log(result)
  var options = {
    pidList: result,
    signal: '-9'
  };



When i console log the result i still see the chrome.exe pid in the list .

Atleast is there another alternate solution for this ?

**Comment by xsellier** [comment]
I suggest you VSCode to debug your application, so you will be able to check why it does not work.
